apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: acru5jb5ydbxa2ee.azurecr.io/samples/nginx
        ports:
        - containerPort: 8080
      # nodeSelector:
      #   kubernetes.io/os: 'windows'
      #   kubernetes.io/arch: 'amd64'
      #   node.kubernetes.io/windows-build: '10.0.17763'
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: nginx